### ISSUE TITLE
simple_psat: No longer need RBAC configuration for Agent

### ISSUE THREAD

**Issue by hiyosi** [spiffe/spire-examples#8]
Later than  https://github.com/spiffe/spire/pull/922,  SPIRE Agent no longer calls K8s API in the PSAT Node Attestor Plugin. 
Therefore, I think we don't need ClusterRole and ClusterRoleBinding for SPIRE Agent.

https://github.com/spiffe/spire-examples/blob/master/examples/k8s/simple_psat/spire-agent.yaml#L8-L34

**Comment by hiyosi** [comment]
But, If we use the [Workload Registrar](https://github.com/spiffe/spire/tree/master/support/k8s/k8s-workload-registrar),  the RBAC configuration like above is required.

**Comment by lucianozablocki** [comment]
Hi @hiyosi! After a little bit of testing, I found out that node attestation using PSAT Node Attestor Plugin keeps working well after agent's _ClusterRole_ and _ClusterRoleBinding_ deletion, but that isn't true for workload attestation. Using k8s WorkloadAttestor, I couldn't properly attest a workload, and I think that's mainly because of the need for pod information when the attestation is attempted (something that the role allows to). Following this reasoning, and though node attestation can work without the agent's _ClusterRole_ and _ClusterRoleBinding_, my opinion is that we should leave the example as it is.
What do you think about it? Is there something that I'm missing in my reasoning? If so, please let me know

**Comment by hiyosi** [comment]
@lucianozablocki Thanks for testing. You are right!
Perhaps I l didn't care of the Workload Attestor.

**Comment by hiyosi** [comment]
I'll close this issue. thanks!
